import React, { useMemo, useState } from 'react';
import { ArrowRight, FileSpreadsheet, Plus, RefreshCw, ShieldCheck, Trash2, X, Search, CheckCircle2, AlertTriangle } from 'lucide-react';
import { BOQItem, CommercialTerms, Financials, HardwareItem, SizingResult } from '../types';
import { assessHardwareSuitability, generateRecommendedBOQ } from '../utils/solarCalculator';

interface Props {
  boq: BOQItem[]; setBoq: React.Dispatch<React.SetStateAction<BOQItem[]>>; sizing: SizingResult;
  financials: Financials; setFinancials: React.Dispatch<React.SetStateAction<Financials>>;
  commercialTerms: CommercialTerms; setCommercialTerms: React.Dispatch<React.SetStateAction<CommercialTerms>>;
  currency: string; inventory: HardwareItem[]; onProceedToPreview: () => void; onPanelWattageChange?: (watts:number)=>void; onSystemVoltageChange?: (volts:number)=>void; knowledgeBase?: {updatedAt:string; sourceCount:number; sources:string[]; summary:string};
}
const money=(n:number)=>Number(n||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});

export const BOQEditor: React.FC<Props> = ({ boq,setBoq,sizing,financials,setFinancials,commercialTerms,setCommercialTerms,currency,inventory,onProceedToPreview,onPanelWattageChange,onSystemVoltageChange,knowledgeBase }) => {
  const [showAdd,setShowAdd]=useState(false);
  const [editing,setEditing]=useState<BOQItem|null>(null);
  const [productSearch,setProductSearch]=useState('');
  const [newItem,setNewItem]=useState<Partial<BOQItem>>({category:'Accessories',description:'',specification:'',qty:1,unit:'pcs',unitPrice:0});
  const regenerate=()=>{
    if(!sizing.totalDailyKwh){alert('Enter at least one load before generating the BOQ.');return;}
    setBoq(generateRecommendedBOQ(sizing,inventory,currency));
  };
  const update=(id:string,field:keyof BOQItem,value:any)=>setBoq(prev=>prev.map(x=>{if(x.id!==id)return x;const y={...x,[field]:value};if(field==='qty'||field==='unitPrice')y.totalPrice=(Number(y.qty)||0)*(Number(y.unitPrice)||0);return y;}));
  const add=(e:React.FormEvent)=>{e.preventDefault();if(!newItem.description?.trim())return;const qty=Number(newItem.qty)||1, price=Number(newItem.unitPrice)||0;setBoq(prev=>[...prev,{id:`cust-${Date.now()}`,category:(newItem.category||'Accessories') as BOQItem['category'],code:`CUST-${Date.now().toString().slice(-5)}`,description:newItem.description!.trim(),specification:newItem.specification||'',qty,unit:newItem.unit||'pcs',unitPrice:price,totalPrice:qty*price}]);setShowAdd(false);setNewItem({category:'Accessories',description:'',specification:'',qty:1,unit:'pcs',unitPrice:0});};
  const candidates = useMemo(()=>{
    if(!editing) return [];
    const text=productSearch.toLowerCase().trim();
    const cat=editing.category;
    return inventory.filter(x=>x.category===cat && `${x.name} ${x.code} ${x.rating} ${x.specification}`.toLowerCase().includes(text)).sort((a,b)=>{
      const one=(x:HardwareItem)=>/one\s*inverter/i.test(`${x.name} ${x.code} ${x.specification}`)?1:0;
      if(one(b)!==one(a)) return one(b)-one(a);
      if(cat==='Solar Panels'){ const wa=Number((a.rating||'').match(/(\d+(?:\.\d+)?)\s*W/i)?.[1]||0); const wb=Number((b.rating||'').match(/(\d+(?:\.\d+)?)\s*W/i)?.[1]||0); return wb-wa; }
      return Number(b.unitPrice||0)-Number(a.unitPrice||0);
    }).slice(0,12);
  },[editing,inventory,productSearch]);
  const applyProduct=(product:HardwareItem)=>{
    if(!editing)return;
    const next={...editing,code:product.code,description:product.name,specification:product.specification,unit:product.unit,unitPrice:Number(product.unitPrice)||0};
    if(product.category==='Solar Panels'){ const w=Number((product.rating||'').match(/(\d+(?:\.\d+)?)\s*W/i)?.[1]||0); if(w){onPanelWattageChange?.(w); const target=sizing.totalDailyKwh/(Math.max(1,sizing.sunHours)*Math.max(0.55,sizing.pvDerate||0.8)); next.qty=Math.max(1,Math.ceil((target*1000)/w));} }
    if(product.category==='Battery Storage'){ const m=`${product.rating} ${product.specification}`.match(/(\d+(?:\.\d+)?)\s*kWh/i); const kwh=m?Number(m[1]):0; if(kwh) next.qty=Math.max(1,Math.ceil(sizing.recommendedBatteryKwh/kwh)); const vm=`${product.rating} ${product.specification}`.match(/(\d+(?:\.\d+)?)\s*V/i); if(vm) onSystemVoltageChange?.(Number(vm[1])); }
    setBoq(prev=>prev.map(x=>x.id===editing.id?{...next,totalPrice:(Number(next.qty)||0)*(Number(next.unitPrice)||0)}:x));
    setEditing(null); setProductSearch('');
  };

  React.useEffect(()=>{const subtotal=boq.reduce((s,x)=>s+(Number(x.totalPrice)||0),0);const discount=Math.min(subtotal,Math.max(0,Number(financials.discount)||0));const taxable=subtotal-discount;const vat=taxable*(Number(financials.vatRate)||0)/100;setFinancials(p=>({...p,subtotal,vatAmount:vat,grandTotal:taxable+vat}));},[boq,financials.discount,financials.vatRate,setFinancials]);

  return <div className="space-y-5 pb-12">
    <section className="bg-white border border-slate-200 rounded-2xl p-6 flex flex-col lg:flex-row lg:items-center justify-between gap-4">
      <div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center"><FileSpreadsheet size={20}/></div><div><div className="text-[11px] uppercase tracking-[.18em] text-emerald-700 font-black">Commercial BOQ</div><h1 className="text-xl font-black text-slate-950">Bill of Quantities</h1><p className="text-xs text-slate-500 mt-1">Prices and specifications are pulled from the editable master hardware database.</p>{knowledgeBase?.sourceCount?<p className="text-[10px] text-emerald-700 mt-1 font-semibold">Source knowledge indexed from {knowledgeBase.sourceCount} document(s).</p>:null}</div></div>
      <div className="flex gap-2"><button onClick={regenerate} className="inline-flex items-center gap-2 border border-slate-300 rounded-lg px-3 py-2 text-xs font-bold text-slate-700 hover:border-emerald-500"><RefreshCw size={14}/> Rebuild from sizing</button><button onClick={()=>setShowAdd(true)} className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg px-3 py-2 text-xs font-black"><Plus size={14}/> Add item</button></div>
    </section>

    <section className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      <div className="px-5 py-4 border-b border-slate-200 flex justify-between"><div><h2 className="font-black text-sm">Equipment & works</h2><p className="text-[10px] text-slate-500">{boq.length} line items • editable quantity and selling price</p></div><div className="text-xs text-slate-500">System: <b className="text-slate-900">{sizing.recommendedInverterKw} kW / {sizing.recommendedPvArrayKwp} kWp / {sizing.recommendedBatteryKwh} kWh</b></div></div>
      {boq.length===0?<div className="p-14 text-center"><FileSpreadsheet className="mx-auto text-slate-300" size={32}/><p className="mt-3 font-bold text-slate-700">No BOQ lines yet</p><button onClick={regenerate} className="mt-3 bg-emerald-600 text-white px-4 py-2 rounded-lg text-xs font-black">Generate from sizing</button></div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-emerald-600 text-white"><tr><th className="px-3 py-2.5 text-left">#</th><th className="px-3 text-left">Item / specification</th><th className="px-2 text-center">Qty</th><th className="px-2 text-center">Unit</th><th className="px-3 text-right">Rate (KSh)</th><th className="px-3 text-right">Amount (KSh)</th><th></th></tr></thead><tbody>{boq.map((x,i)=><tr key={x.id} onClick={()=>setEditing(x)} className="border-b border-slate-100 align-top hover:bg-slate-50 cursor-pointer"><td className="px-3 py-3 text-slate-400 font-mono">{i+1}</td><td className="px-3 py-3 min-w-[340px]"><div className="text-[9px] text-emerald-700 font-black uppercase tracking-wider mb-1">Click line to change from database</div><div className="font-bold text-slate-900">{x.description}</div><div className="text-[10px] text-slate-500 mt-1">{x.specification}</div><div className="text-[9px] uppercase tracking-wider text-emerald-700 mt-1 font-bold">{x.code} • {x.category}</div></td><td className="px-2 py-3"><input className="w-16 border border-slate-300 rounded-md px-2 py-1 text-center" type="number" min="1" value={x.qty} onClick={e=>e.stopPropagation()} onChange={e=>update(x.id,'qty',Number(e.target.value)||1)}/></td><td className="px-2 py-3 text-center text-slate-500">{x.unit}</td><td className="px-3 py-3 text-right"><input className="w-28 border border-slate-300 rounded-md px-2 py-1 text-right" type="number" min="0" value={x.unitPrice} onClick={e=>e.stopPropagation()} onChange={e=>update(x.id,'unitPrice',Number(e.target.value)||0)}/></td><td className="px-3 py-3 text-right font-mono font-black text-slate-900">{money(x.totalPrice)}</td><td className="px-2 py-3 text-center"><button onClick={()=>setBoq(p=>p.filter(y=>y.id!==x.id))} className="text-slate-400 hover:text-rose-600"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}
    </section>

    <div className="grid lg:grid-cols-[1fr_320px] gap-5">
      <section className="bg-white border border-slate-200 rounded-xl p-5"><div className="flex items-center gap-2 mb-4"><ShieldCheck size={17} className="text-emerald-700"/><h2 className="font-black text-sm">Commercial terms & warranty</h2></div><div className="grid md:grid-cols-2 gap-3 text-xs"><label className="font-bold text-slate-600">Payment terms<input className="field" value={commercialTerms.paymentTerms} onChange={e=>setCommercialTerms(p=>({...p,paymentTerms:e.target.value}))}/></label><label className="font-bold text-slate-600">Installation period<input className="field" value={commercialTerms.installationPeriod} onChange={e=>setCommercialTerms(p=>({...p,installationPeriod:e.target.value}))}/></label><label className="font-bold text-slate-600">PV warranty<input className="field" value={commercialTerms.warrantyPanels} onChange={e=>setCommercialTerms(p=>({...p,warrantyPanels:e.target.value}))}/></label><label className="font-bold text-slate-600">Inverter warranty<input className="field" value={commercialTerms.warrantyInverter} onChange={e=>setCommercialTerms(p=>({...p,warrantyInverter:e.target.value}))}/></label><label className="font-bold text-slate-600 md:col-span-2">Battery warranty<input className="field" value={commercialTerms.warrantyBattery} onChange={e=>setCommercialTerms(p=>({...p,warrantyBattery:e.target.value}))}/></label></div></section>
      <section className="bg-white border border-slate-200 rounded-xl p-5"><h2 className="font-black text-sm border-b border-slate-200 pb-3">Quotation total</h2><div className="space-y-3 text-xs mt-4"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><b>{currency}{money(financials.subtotal)}</b></div><div className="flex justify-between items-center"><span className="text-slate-500">Discount</span><input className="w-28 border rounded-md px-2 py-1 text-right" type="number" min="0" value={financials.discount} onChange={e=>setFinancials(p=>({...p,discount:Number(e.target.value)||0}))}/></div><div className="flex justify-between items-center"><span className="text-slate-500">VAT</span><select className="border rounded-md px-2 py-1" value={financials.vatRate} onChange={e=>setFinancials(p=>({...p,vatRate:Number(e.target.value)}))}><option value={0}>0%</option><option value={16}>16%</option></select></div><div className="border-t border-slate-200 pt-3 flex justify-between items-end"><span className="font-black">Grand total</span><b className="text-lg text-emerald-700">{currency}{money(financials.grandTotal)}</b></div></div><button onClick={onProceedToPreview} disabled={!boq.length} className="w-full mt-5 bg-emerald-600 hover:bg-emerald-700 disabled:bg-slate-300 text-white rounded-lg py-2.5 text-xs font-black inline-flex items-center justify-center gap-2">Preview clean quotation <ArrowRight size={15}/></button></section>
    </div>

    {editing&&<div className="fixed inset-0 z-50 bg-slate-950/30 flex items-center justify-center p-4"><div className="bg-white rounded-xl w-full max-w-2xl border border-slate-200 shadow-2xl p-5"><div className="flex justify-between items-center mb-4"><div><h3 className="font-black">Change BOQ line item</h3><p className="text-xs text-slate-500">Choose a product from the master database. The quantity and sizing checks update from the selected specification.</p></div><button onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="flex gap-2 mb-3"><div className="search-control flex-1"><Search size={14}/><input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder="Search product, rating or code..."/></div></div><div className="space-y-2 max-h-[420px] overflow-auto">{candidates.map(product=>{const check=assessHardwareSuitability(product,sizing);return <button key={product.id} onClick={()=>applyProduct(product)} className="w-full text-left border border-slate-200 rounded-lg p-3 hover:border-emerald-500 hover:bg-emerald-50/40"><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-slate-900">{product.name}</b><div className="text-[10px] text-slate-500 mt-1">{product.rating} • {product.code} • KSh {money(product.unitPrice)}</div><div className="text-[10px] text-slate-500 mt-1">{product.specification}</div></div><div className="shrink-0 text-right">{check.suitable?<span className="text-emerald-700 font-bold inline-flex gap-1 items-center"><CheckCircle2 size={13}/> Suitable</span>:<span className="text-amber-700 font-bold inline-flex gap-1 items-center"><AlertTriangle size={13}/> Review</span>}</div></div>{check.warnings.length>0&&<div className="text-[10px] text-amber-700 mt-2">{check.warnings.join(' ')}</div>}</button>})}{!candidates.length&&<div className="p-8 text-center text-sm text-slate-500">No matching products in this category.</div>}</div></div></div>}

    {showAdd&&<div className="fixed inset-0 z-50 bg-slate-950/30 flex items-center justify-center p-4"><div className="bg-white rounded-xl w-full max-w-lg border border-slate-200 shadow-2xl p-5"><div className="flex justify-between items-center mb-4"><h3 className="font-black">Add custom BOQ item</h3><button onClick={()=>setShowAdd(false)}><X size={18}/></button></div><form onSubmit={add} className="space-y-3 text-xs"><input className="field" placeholder="Description" value={newItem.description||''} onChange={e=>setNewItem(p=>({...p,description:e.target.value}))} required/><textarea className="field min-h-24" placeholder="Specification" value={newItem.specification||''} onChange={e=>setNewItem(p=>({...p,specification:e.target.value}))}/><div className="grid grid-cols-3 gap-2"><input className="field" type="number" min="1" placeholder="Qty" value={newItem.qty} onChange={e=>setNewItem(p=>({...p,qty:Number(e.target.value)}))}/><input className="field" placeholder="Unit" value={newItem.unit||''} onChange={e=>setNewItem(p=>({...p,unit:e.target.value}))}/><input className="field" type="number" min="0" placeholder="Rate" value={newItem.unitPrice} onChange={e=>setNewItem(p=>({...p,unitPrice:Number(e.target.value)}))}/></div><button className="w-full bg-emerald-600 text-white rounded-lg py-2.5 font-black">Add item</button></form></div></div>}
  </div>;
};
