import React, { useMemo, useState } from 'react';
import { Database, Download, Edit3, Eye, FileText, Image as ImageIcon, Package, Plus, Search, Trash2, Upload, X, BrainCircuit, LoaderCircle } from 'lucide-react';
import { Appliance, DatabaseDocument, GalleryImage, HardwareItem, Quotation } from '../types';
import { ClientRecordCard } from './ClientRecordCard';
import { learnFromDatabaseDocuments } from '../services/api';

interface Props { appliances:Appliance[]; inventory:HardwareItem[]; quotes:Quotation[]; images:GalleryImage[]; documents:DatabaseDocument[]; onSaveAppliance:(x:Appliance)=>Promise<void>; onDeleteAppliance:(id:string)=>Promise<void>; onSaveHardware:(x:HardwareItem)=>Promise<void>; onDeleteHardware:(id:string)=>Promise<void>; onSaveImage:(x:GalleryImage)=>Promise<void>; onDeleteImage:(id:string)=>Promise<void>; onSaveDocument:(x:DatabaseDocument)=>Promise<void>; onDeleteDocument:(id:string)=>Promise<void>; onDeleteQuote:(id:string)=>Promise<void>; onOpenQuote:(q:Quotation)=>void; onRefreshDatabase:()=>Promise<void>; onStartNewQuotation?:()=>void; }
type Tab='hardware'|'appliances'|'images'|'documents'|'quotes';
const money=(n:number)=>Number(n||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
const readData=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});

export const DatabaseManager:React.FC<Props>=props=>{
 const {appliances,inventory,quotes,images,documents,onSaveAppliance,onDeleteAppliance,onSaveHardware,onDeleteHardware,onSaveImage,onDeleteImage,onSaveDocument,onDeleteDocument,onDeleteQuote,onOpenQuote,onRefreshDatabase}=props;
 const [tab,setTab]=useState<Tab>('hardware'); const [search,setSearch]=useState(''); const [category,setCategory]=useState('All');
 const [hardware,setHardware]=useState<HardwareItem|null>(null); const [learning,setLearning]=useState(false); const [learned,setLearned]=useState<string>(''); const [app,setApp]=useState<Appliance|null>(null); const [image,setImage]=useState<GalleryImage|null>(null); const [viewImage,setViewImage]=useState<GalleryImage|null>(null); const [busy,setBusy]=useState(false);
 const q=(search||'').toLowerCase().trim();
 const hardwareRows=useMemo(()=>inventory.filter(x=>(category==='All'||x.category===category)&&`${x.name} ${x.code} ${x.rating}`.toLowerCase().includes(q)),[inventory,category,q]);
 const appRows=useMemo(()=>appliances.filter(x=>(category==='All'||x.category===category)&&`${x.name} ${x.category}`.toLowerCase().includes(q)),[appliances,category,q]);
 const imageRows=useMemo(()=>images.filter(x=>(category==='All'||x.category===category)&&`${x.title} ${x.category}`.toLowerCase().includes(q)),[images,category,q]);
 const docRows=useMemo(()=>documents.filter(x=>`${x.name} ${x.category}`.toLowerCase().includes(q)),[documents,q]);
 const quoteRows=useMemo(()=>quotes.filter(x=>`${x.quoteNumber} ${x.clientRef} ${x.client?.name||''} ${x.client?.phone||''}`.toLowerCase().includes(q)),[quotes,q]);
 const categories=tab==='hardware'?['All',...Array.from(new Set(inventory.map(x=>x.category)))] : tab==='appliances'?['All',...Array.from(new Set(appliances.map(x=>x.category)))] : tab==='images'?['All',...Array.from(new Set(images.map(x=>x.category)))] : ['All'];
 const saveHardware=async()=>{if(!hardware?.name.trim())return;setBusy(true);try{await onSaveHardware({...hardware,name:hardware.name.trim()})}finally{setBusy(false);setHardware(null)}};
 const saveApp=async()=>{if(!app?.name.trim())return;setBusy(true);try{await onSaveAppliance({...app,name:app.name.trim()})}finally{setBusy(false);setApp(null)}};
 const saveImage=async()=>{if(!image?.title.trim()||!image.imageUrl)return;setBusy(true);try{await onSaveImage({...image,title:image.title.trim()})}finally{setBusy(false);setImage(null)}};
 const uploadImage=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setImage({id:`img-${Date.now()}`,title:f.name.replace(/\.[^.]+$/,''),category:'Site Photo',imageUrl:await readData(f),caption:'',uploadedAt:new Date().toISOString()});e.target.value=''};
 const uploadDoc=async(e:React.ChangeEvent<HTMLInputElement>,linked?:{id:string,type:'hardware'|'appliance'|'gallery'})=>{const f=e.target.files?.[0];if(!f)return;if(f.size>12*1024*1024){alert('Database documents must be 12 MB or smaller.');e.target.value='';return}const data=await readData(f);await onSaveDocument({id:`doc-${Date.now()}`,name:f.name,mimeType:f.type||'application/pdf',dataUrl:data,size:f.size,category: f.name.toLowerCase().endsWith('.xlsx')||f.name.toLowerCase().endsWith('.xls')||f.name.toLowerCase().endsWith('.csv') ? 'Excel / Spreadsheet' : /catalogue/i.test(f.name) ? 'Catalogue' : /boq|price/i.test(f.name) ? 'BOQ / Price List' : 'Product Datasheet',linkedItemId:linked?.id,linkedItemType:linked?.type,uploadedAt:new Date().toISOString()});e.target.value=''};
 const exportDb=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),appliances,inventory,images,documents,quotes},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=`ONE_INVERTER_DATABASE_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 const tabs:[Tab,string,number][]=[['hardware','Hardware',inventory.length],['appliances','Load library',appliances.length],['images','Images',images.length],['documents','Source documents',documents.length],['quotes','Quotations',quotes.length]];
 return <div className="page-stack">
  <section className="page-header"><div className="page-heading"><div className="section-icon"><Database size={18}/></div><div><div className="eyebrow">Master database</div><h1>Equipment, loads, images & quotations</h1><p>One source of truth for sizing and BOQ generation. Keep product records editable and documents attached to the correct item.</p></div></div><div className="toolbar-actions"><button className="btn-secondary" onClick={onRefreshDatabase}>Refresh</button><button className="btn-secondary" disabled={learning} onClick={async()=>{setLearning(true);setLearned('');try{const r=await learnFromDatabaseDocuments();setLearned(`Learned from ${r.sourceCount} document(s) • ${new Date(r.updatedAt).toLocaleString()}`)}catch(e:any){setLearned(e?.message||'Learning failed')}finally{setLearning(false)}}}>{learning?<LoaderCircle size={14} className="animate-spin"/>:<BrainCircuit size={14}/>} {learning?'Learning…':'Learn from database docs'}</button><button className="btn-secondary" onClick={exportDb}><Download size={14}/> Export</button></div></section>
  <section className="panel database-panel">
   {learned&&<div className="mx-4 mt-4 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-800">{learned}</div>}
   <div className="database-tabs">{tabs.map(([id,label,count])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setCategory('All');setSearch('')}}>{label}<span>{count}</span></button>)}</div>
   <div className="database-toolbar"><div className="search-control"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${tab === 'quotes' ? 'client or quotation' : 'this section'}...`}/></div>{tab!=='documents'&&tab!=='quotes'&&<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select>}{tab==='hardware'&&<button className="btn-primary" onClick={()=>setHardware({id:`hw-${Date.now()}`,category:'Inverter & MPPT',code:'NEW-ITEM',name:'',rating:'',specification:'',unit:'pcs',unitPrice:0,inStock:true})}><Plus size={15}/> Add hardware</button>}{tab==='appliances'&&<button className="btn-primary" onClick={()=>setApp({id:`app-${Date.now()}`,name:'',category:'Other',watts:0,qty:1,hoursPerDay:1,usagePercent:100,surgeMultiplier:1.2,nightUsagePercent:0})}><Plus size={15}/> Add load</button>}{tab==='images'&&<label className="btn-primary"><Upload size={15}/> Upload image<input hidden type="file" accept="image/*,.svg" onChange={uploadImage}/></label>}{tab==='documents'&&<label className="btn-primary"><Upload size={15}/> Upload source document<input hidden type="file" accept="application/pdf,.pdf,.xlsx,.xls,.csv,.docx,.txt" onChange={e=>uploadDoc(e)}/></label>}</div>

   {tab==='hardware'&&<div className="table-wrap"><table className="clean-table"><thead><tr><th>Product</th><th>Rating</th><th>Unit</th><th className="num">Price (KSh)</th><th className="actions-col">Actions</th></tr></thead><tbody>{hardwareRows.map(x=><tr key={x.id}><td><div className="product-cell"><div className="thumb">{x.imageUrl?<img src={x.imageUrl}/>:<Package size={17}/>}</div><div><b>{x.name||'Unnamed hardware'}</b><small>{x.code} • {x.category}</small></div></div></td><td>{x.rating||'—'}</td><td>{x.unit}</td><td className="num">KSh {money(x.unitPrice)}</td><td className="actions-col"><button className="icon-action" title="Edit product, image and PDF" onClick={()=>setHardware({...x})}><Edit3 size={14}/></button><button className="btn-secondary btn-small" onClick={()=>setHardware({...x})}>Edit product</button><button className="icon-action danger" onClick={()=>onDeleteHardware(x.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!hardwareRows.length&&<Empty/>}</div>}
   {tab==='appliances'&&<div className="table-wrap"><table className="clean-table"><thead><tr><th>Load</th><th>Category</th><th>W</th><th>Qty</th><th>Hours</th><th>Use</th><th className="actions-col">Actions</th></tr></thead><tbody>{appRows.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.category}</td><td>{x.watts}</td><td>{x.qty}</td><td>{x.hoursPerDay}</td><td>{x.usagePercent??100}%</td><td className="actions-col"><button className="btn-secondary btn-small" onClick={()=>setApp({...x})}><Edit3 size={13}/> Edit</button><button className="icon-action danger" onClick={()=>onDeleteAppliance(x.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!appRows.length&&<Empty/>}</div>}
   {tab==='images'&&<div className="image-library">{imageRows.map(x=><div className="image-card" key={x.id}><div className="image-card-media"><img src={x.imageUrl}/></div><div className="image-card-body"><b>{x.title}</b><small>{x.category}</small><div className="image-card-actions"><button className="btn-secondary btn-small" onClick={()=>setViewImage(x)}><Eye size={13}/> View</button><button className="btn-secondary btn-small" onClick={()=>setImage({...x})}><Edit3 size={13}/></button><button className="icon-action danger" onClick={()=>onDeleteImage(x.id)}><Trash2 size={14}/></button></div></div></div>)}{!imageRows.length&&<Empty/>}</div>}
   {tab==='documents'&&<div className="document-list">{docRows.map(d=><div className="document-row" key={d.id}><div className="document-icon"><FileText size={17}/></div><div className="document-info"><b>{d.name}</b><small>{d.category} • {(d.size/1024/1024).toFixed(2)} MB{d.linkedItemId?' • linked to product':''}</small></div><div className="toolbar-actions"><a className="btn-secondary btn-small" href={d.dataUrl} download={d.name}>Download</a><button className="icon-action danger" onClick={()=>onDeleteDocument(d.id)}><Trash2 size={14}/></button></div></div>)}{!docRows.length&&<Empty/>}</div>}
   {tab==='quotes'&&<div className="records-list embedded-records">{quoteRows.map(q=><ClientRecordCard key={q.id} quote={q} onOpen={()=>onOpenQuote(q)} onDelete={()=>{if(window.confirm(`Delete quotation ${q.quoteNumber}?`))onDeleteQuote(q.id)}}/>)}{!quoteRows.length&&<Empty/>}</div>}
  </section>

  {hardware&&<Modal title="Edit hardware product" close={()=>setHardware(null)}><div className="form-grid two"><label className="form-field"><span>Product name</span><input value={hardware.name} onChange={e=>setHardware({...hardware,name:e.target.value})}/></label><label className="form-field"><span>Code</span><input value={hardware.code} onChange={e=>setHardware({...hardware,code:e.target.value})}/></label><label className="form-field"><span>Rating</span><input value={hardware.rating} onChange={e=>setHardware({...hardware,rating:e.target.value})}/></label><label className="form-field"><span>Unit price (KSh)</span><input type="number" min="0" value={hardware.unitPrice} onChange={e=>setHardware({...hardware,unitPrice:Number(e.target.value)||0})}/></label><label className="form-field full"><span>Specification</span><textarea rows={5} value={hardware.specification} onChange={e=>setHardware({...hardware,specification:e.target.value})}/></label></div><div className="upload-box"><div className="upload-preview">{hardware.imageUrl?<img src={hardware.imageUrl}/>:<ImageIcon size={24}/>}</div><div><b>Product image</b><small>Upload or replace the image used in the master catalogue.</small><label className="btn-secondary btn-small"><Upload size={13}/> Choose image<input hidden type="file" accept="image/*,.svg" onChange={async e=>{const f=e.target.files?.[0];if(f)setHardware({...hardware,imageUrl:await readData(f)});e.target.value=''}}/></label></div></div><div className="upload-box"><div className="document-icon"><FileText size={20}/></div><div><b>Datasheet / manual PDF</b><small>Attach the document directly to this hardware record.</small><label className="btn-secondary btn-small"><Upload size={13}/> Upload source document<input hidden type="file" accept="application/pdf,.pdf,.xlsx,.xls,.csv,.docx,.txt" onChange={e=>uploadDoc(e,{id:hardware.id,type:'hardware'})}/></label>{documents.filter(d=>d.linkedItemId===hardware.id).map(d=><a key={d.id} className="document-link" href={d.dataUrl} download={d.name}>{d.name}</a>)}</div></div><div className="modal-footer"><button className="btn-secondary" onClick={()=>setHardware(null)}>Cancel</button><button className="btn-primary" disabled={busy} onClick={saveHardware}>Save product</button></div></Modal>}
  {app&&<Modal title="Edit load library item" close={()=>setApp(null)}><div className="form-grid two"><label className="form-field full"><span>Load name</span><input value={app.name} onChange={e=>setApp({...app,name:e.target.value})}/></label><label className="form-field"><span>Watts</span><input type="number" min="0" value={app.watts} onChange={e=>setApp({...app,watts:Number(e.target.value)||0})}/></label><label className="form-field"><span>Quantity</span><input type="number" min="1" value={app.qty} onChange={e=>setApp({...app,qty:Number(e.target.value)||1})}/></label><label className="form-field"><span>Hours/day</span><input type="number" min="0" max="24" step="0.1" value={app.hoursPerDay} onChange={e=>setApp({...app,hoursPerDay:Number(e.target.value)||0})}/></label><label className="form-field"><span>Usage %</span><input type="number" min="0" max="100" value={app.usagePercent??100} onChange={e=>setApp({...app,usagePercent:Number(e.target.value)})}/></label></div><div className="modal-footer"><button className="btn-secondary" onClick={()=>setApp(null)}>Cancel</button><button className="btn-primary" onClick={saveApp}>Save load</button></div></Modal>}
  {image&&<Modal title="Edit image" close={()=>setImage(null)}><label className="form-field"><span>Title</span><input value={image.title} onChange={e=>setImage({...image,title:e.target.value})}/></label><label className="form-field"><span>Category</span><select value={image.category} onChange={e=>setImage({...image,category:e.target.value as GalleryImage['category']})}><option>System Schematic</option><option>Single Line Diagram</option><option>Roof Panel Layout</option><option>Inverter Installation</option><option>Battery Bank</option><option>Site Photo</option></select></label><label className="form-field"><span>Caption</span><textarea rows={3} value={image.caption||''} onChange={e=>setImage({...image,caption:e.target.value})}/></label><div className="modal-image"><img src={image.imageUrl}/></div><label className="btn-secondary"><Upload size={14}/> Replace image<input hidden type="file" accept="image/*,.svg" onChange={async e=>{const f=e.target.files?.[0];if(f)setImage({...image,imageUrl:await readData(f)});e.target.value=''}}/></label><div className="modal-footer"><button className="btn-secondary" onClick={()=>setImage(null)}>Cancel</button><button className="btn-primary" onClick={saveImage}>Save image</button></div></Modal>}
  {viewImage&&<div className="modal-backdrop" onClick={()=>setViewImage(null)}><div className="image-viewer" onClick={e=>e.stopPropagation()}><div className="modal-title"><div><b>{viewImage.title}</b><small>{viewImage.category}</small></div><button onClick={()=>setViewImage(null)}><X size={18}/></button></div><img src={viewImage.imageUrl}/></div></div>}
 </div>;
};
const Empty=()=> <div className="empty-state"><Database size={27}/><strong>No records</strong><span>Nothing matches this view.</span></div>;
const Modal:React.FC<{title:string;close:()=>void;children:React.ReactNode}>=({title,close,children})=><div className="modal-backdrop"><div className="modal"><div className="modal-title"><b>{title}</b><button onClick={close}><X size={18}/></button></div><div className="modal-body">{children}</div></div></div>;
