import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BatteryCharging, Download, FileText, Gauge, RefreshCw, Trash2, Wifi, Zap } from 'lucide-react';
import jsPDF from 'jspdf';
import { Client, InverterTelemetry } from '../types';
import { deleteTelemetry, fetchTelemetry, saveTelemetry } from '../services/api';

interface Props { clients: Client[]; selectedClient?: Client | null; onBackToRecords?: () => void; }
const blank=(clients:Client[]):InverterTelemetry=>({id:`tel-${Date.now()}`,clientRef:clients[0]?.refNumber||'',clientName:clients[0]?.name||'',inverterModel:'',serialNumber:'',site:'',timestamp:new Date().toISOString(),pvPowerKw:0,loadPowerKw:0,batteryPowerKw:0,batterySoc:0,gridPowerKw:0,dailyEnergyKwh:0,totalEnergyKwh:0,status:'Online'});
const n=(v:any)=>Number(v||0); const fmt=(v:any,d=1)=>n(v).toLocaleString('en-KE',{maximumFractionDigits:d});

export const InverterMonitoring:React.FC<Props>=({clients,selectedClient,onBackToRecords})=>{
 const [rows,setRows]=useState<InverterTelemetry[]>([]); const [clientRef,setClientRef]=useState(selectedClient?.refNumber || clients[0]?.refNumber || 'all'); const [period,setPeriod]=useState('7d'); const [form,setForm]=useState(blank(clients)); const [loading,setLoading]=useState(false); const [autoRefresh,setAutoRefresh]=useState(true);
 const load=async()=>{setLoading(true);try{setRows(await fetchTelemetry())}finally{setLoading(false)}};
 useEffect(()=>{load()},[]); useEffect(()=>{if(!autoRefresh)return;const id=window.setInterval(load,30000);return()=>window.clearInterval(id)},[autoRefresh]);
 useEffect(()=>{if(selectedClient?.refNumber){setClientRef(selectedClient.refNumber);setForm(f=>({...f,clientRef:selectedClient.refNumber,clientName:selectedClient.name,site:selectedClient.address||f.site}));}},[selectedClient]); useEffect(()=>{if(!form.clientRef&&clients[0])setForm(f=>({...f,clientRef:clients[0].refNumber,clientName:clients[0].name}))},[clients]);
 const filtered=useMemo(()=>{const cutoff=period==='all'?0:Date.now()-(period==='24h'?86400000:7*86400000);return rows.filter(r=>(clientRef==='all'||r.clientRef===clientRef)&&new Date(r.timestamp).getTime()>=cutoff).sort((a,b)=>new Date(b.timestamp).getTime()-new Date(a.timestamp).getTime())},[rows,clientRef,period]);
 const latest=filtered[0];
 const daily=useMemo(()=>{const map=new Map<string,{date:string,energy:number,total:number,readings:number}>();[...filtered].reverse().forEach(r=>{const d=new Date(r.timestamp).toLocaleDateString('en-CA');const cur=map.get(d)||{date:d,energy:0,total:0,readings:0};cur.energy=Math.max(cur.energy,n(r.dailyEnergyKwh));cur.total=Math.max(cur.total,n(r.totalEnergyKwh));cur.readings++;map.set(d,cur)});return [...map.values()].slice(-7)},[filtered]);
 const update=(k:keyof InverterTelemetry,v:any)=>setForm(f=>({...f,[k]:v}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!form.clientRef&&clients.length) return;const c=clients.find(x=>x.refNumber===form.clientRef);const saved=await saveTelemetry({...form,clientName:c?.name||form.clientName,timestamp:new Date().toISOString()});setRows(r=>[saved,...r.filter(x=>x.id!==saved.id)]);setForm(blank(clients))};
 const remove=async(id:string)=>{if(confirm('Delete this telemetry reading?')){await deleteTelemetry(id);setRows(r=>r.filter(x=>x.id!==id))}};
 const exportCsv=()=>{const h=['Client Ref','Client','Inverter','Serial','Site','Timestamp','PV kW','Load kW','Battery kW','SOC %','Grid kW','Daily kWh','Total kWh','Status'];const lines=filtered.map(r=>[r.clientRef,r.clientName,r.inverterModel,r.serialNumber||'',r.site||'',r.timestamp,r.pvPowerKw,r.loadPowerKw,r.batteryPowerKw,r.batterySoc,r.gridPowerKw,r.dailyEnergyKwh,r.totalEnergyKwh,r.status].map(x=>`"${String(x).replace(/"/g,'""')}"`).join(','));const blob=new Blob([[h.join(','),...lines].join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ONE_INVERTER_ENERGY_${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const reportPdf=()=>{const pdf=new jsPDF({unit:'mm',format:'a4'});const green=[22,163,74] as const;const dark=[15,23,42] as const;let y=18;pdf.setFont('helvetica','bold');pdf.setFontSize(18);pdf.setTextColor(...dark);pdf.text('ONE INVERTER',15,y);y+=7;pdf.setFontSize(10);pdf.setTextColor(...green);pdf.text('ENERGY TRACKER REPORT',15,y);y+=8;pdf.setTextColor(...dark);pdf.setFontSize(9);pdf.setFont('helvetica','normal');pdf.text(`Client: ${latest?.clientName||'All clients'}`,15,y);pdf.text(`Period: ${period}`,120,y);y+=5;pdf.text(`Generated: ${new Date().toLocaleString('en-KE')}`,15,y);y+=9;pdf.setFillColor(...green);pdf.rect(15,y,180,7,'F');pdf.setTextColor(255,255,255);pdf.setFont('helvetica','bold');pdf.text('Latest inverter snapshot',18,y+4.8);y+=12;pdf.setTextColor(...dark);pdf.setFont('helvetica','normal');const stats=[['PV power',`${fmt(latest?.pvPowerKw)} kW`],['Load',`${fmt(latest?.loadPowerKw)} kW`],['Battery SOC',`${fmt(latest?.batterySoc)} %`],['Daily energy',`${fmt(latest?.dailyEnergyKwh)} kWh`],['Cumulative energy',`${fmt(latest?.totalEnergyKwh)} kWh`],['Status',latest?.status||'No data']];stats.forEach((s,i)=>{const x=15+(i%3)*60, yy=y+Math.floor(i/3)*13;pdf.setFont('helvetica','bold');pdf.setFontSize(8);pdf.text(s[0],x,yy);pdf.setFont('helvetica','normal');pdf.setFontSize(10);pdf.text(s[1],x,yy+5)});y+=31;pdf.setFont('helvetica','bold');pdf.setFontSize(10);pdf.text('Daily energy history',15,y);y+=5;const max=Math.max(1,...daily.map(d=>d.energy));daily.forEach((d,i)=>{const bar=Math.max(2,120*d.energy/max);pdf.setFillColor(...green);pdf.rect(15,y+i*8,bar,4,'F');pdf.setTextColor(...dark);pdf.setFont('helvetica','normal');pdf.setFontSize(7);pdf.text(`${d.date}  ${fmt(d.energy,2)} kWh`,138,y+3+i*8)});y+=daily.length*8+7;pdf.setFont('helvetica','bold');pdf.setFontSize(10);pdf.text('Recent readings',15,y);y+=6;pdf.setFontSize(7);const headers=['Time','Inverter','PV','Load','SOC','Daily kWh','Status'];const xs=[15,48,90,112,134,150,177];headers.forEach((h,i)=>pdf.text(h,xs[i],y));y+=4;filtered.slice(0,18).forEach(r=>{if(y>282){pdf.addPage();y=18}pdf.setFont('helvetica','normal');pdf.text(new Date(r.timestamp).toLocaleDateString('en-KE'),xs[0],y);pdf.text((r.inverterModel||'-').slice(0,20),xs[1],y);pdf.text(`${fmt(r.pvPowerKw)}`,xs[2],y);pdf.text(`${fmt(r.loadPowerKw)}`,xs[3],y);pdf.text(`${fmt(r.batterySoc)}%`,xs[4],y);pdf.text(`${fmt(r.dailyEnergyKwh,2)}`,xs[5],y);pdf.text(r.status,xs[6],y);y+=5});const safe=(latest?.clientName||'Energy').replace(/[^a-z0-9]+/gi,'_');const blob=pdf.output('blob');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ONE_INVERTER_ENERGY_REPORT_${safe}_${new Date().toISOString().slice(0,10)}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)};
 const maxBar=Math.max(1,...daily.map(x=>x.energy));
 return <div className="space-y-5 pb-12">
  <section className="bg-white border border-slate-200 rounded-2xl p-6"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center"><Activity size={20}/></div><div><div className="text-[11px] uppercase tracking-[.18em] font-black text-emerald-700">Energy monitoring</div><h1 className="text-xl font-black text-slate-950">Smart Inverter Energy Tracker</h1><p className="text-xs text-slate-500 mt-1">Track PV generation, load, battery state, grid contribution and cumulative energy by client/site.</p></div></div><div className="flex flex-wrap gap-2">{onBackToRecords&&<button onClick={onBackToRecords} className="border border-slate-300 rounded-lg px-3 py-2 text-xs font-bold">← Client records</button>}<select className="border border-slate-300 rounded-lg px-3 py-2 text-xs" value={clientRef} onChange={e=>setClientRef(e.target.value)}><option value="all">All clients</option>{clients.map(c=><option key={c.refNumber} value={c.refNumber}>{c.name||c.refNumber}</option>)}</select><select className="border border-slate-300 rounded-lg px-3 py-2 text-xs" value={period} onChange={e=>setPeriod(e.target.value)}><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="all">All history</option></select><button onClick={()=>setAutoRefresh(v=>!v)} className={`border rounded-lg px-3 py-2 text-xs font-bold ${autoRefresh?'border-emerald-300 text-emerald-700':'border-slate-300 text-slate-500'}`}><Wifi size={14} className="inline mr-1"/>{autoRefresh?'Auto 30s':'Auto off'}</button><button onClick={load} className="border border-slate-300 rounded-lg px-3 py-2"><RefreshCw size={14} className={loading?'animate-spin':''}/></button><button onClick={reportPdf} disabled={!filtered.length} className="bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg px-3 py-2 text-xs font-black"><FileText size={14} className="inline mr-1"/>Energy PDF</button><button onClick={exportCsv} className="border border-slate-300 rounded-lg px-3 py-2 text-xs font-bold"><Download size={14} className="inline mr-1"/>CSV</button></div></div></section>

  <section className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[[Zap,'PV power',latest?.pvPowerKw,'kW'],[Gauge,'Load',latest?.loadPowerKw,'kW'],[BatteryCharging,'Battery',latest?.batteryPowerKw,'kW'],[BatteryCharging,'Battery SOC',latest?.batterySoc,'%'],[Activity,'Daily energy',latest?.dailyEnergyKwh,'kWh'],[Activity,'Cumulative',latest?.totalEnergyKwh,'kWh']].map(([Icon,label,value,unit]:any)=><div key={label} className="bg-white border border-slate-200 rounded-xl p-4"><div className="flex gap-2 items-center text-[10px] uppercase tracking-wider font-bold text-slate-500"><Icon size={14} className="text-emerald-700"/>{label}</div><div className="mt-2 text-xl font-black text-slate-950">{fmt(value)} <span className="text-[10px] font-bold text-slate-500">{unit}</span></div></div>)}</section>

  <div className="grid lg:grid-cols-[360px_1fr] gap-5">
   <section className="bg-white border border-slate-200 rounded-xl p-5"><h2 className="font-black text-sm mb-4">Record a telemetry reading</h2><form onSubmit={submit} className="space-y-2.5 text-xs"><label className="font-bold text-slate-600">Client<select className="field" value={form.clientRef} onChange={e=>{const c=clients.find(x=>x.refNumber===e.target.value);setForm(f=>({...f,clientRef:e.target.value,clientName:c?.name||''}))}}><option value="">Select client</option>{clients.map(c=><option key={c.refNumber} value={c.refNumber}>{c.name||c.refNumber}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="font-bold text-slate-600">Inverter<input className="field" value={form.inverterModel} onChange={e=>update('inverterModel',e.target.value)}/></label><label className="font-bold text-slate-600">Serial<input className="field" value={form.serialNumber||''} onChange={e=>update('serialNumber',e.target.value)}/></label></div><label className="font-bold text-slate-600">Site<input className="field" value={form.site||''} onChange={e=>update('site',e.target.value)}/></label><div className="grid grid-cols-2 gap-2">{([['pvPowerKw','PV kW'],['loadPowerKw','Load kW'],['batteryPowerKw','Battery kW'],['batterySoc','SOC %'],['gridPowerKw','Grid kW'],['dailyEnergyKwh','Daily kWh'],['totalEnergyKwh','Cumulative kWh']] as const).map(([k,l])=><label key={k} className="font-bold text-slate-600">{l}<input className="field" type="number" step="0.1" value={(form as any)[k]} onChange={e=>update(k,Number(e.target.value)||0)}/></label>)}</div><label className="font-bold text-slate-600">Status<select className="field" value={form.status} onChange={e=>update('status',e.target.value as any)}><option>Online</option><option>Warning</option><option>Offline</option></select></label><button className="w-full bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg py-2.5 font-black">Save reading</button></form></section>
   <section className="space-y-5"><div className="bg-white border border-slate-200 rounded-xl p-5"><div className="flex justify-between items-center"><div><h2 className="font-black text-sm">Daily generation trend</h2><p className="text-[10px] text-slate-500 mt-1">Highest daily energy reading per day in the selected period.</p></div><span className="text-[10px] font-bold text-slate-500">{daily.length} days</span></div><div className="mt-5 space-y-2">{daily.length?daily.map(d=><div key={d.date} className="grid grid-cols-[72px_1fr_62px] gap-2 items-center text-[10px]"><span className="text-slate-500">{d.date}</span><div className="h-5 bg-slate-100 rounded overflow-hidden"><div className="h-full bg-emerald-500" style={{width:`${Math.max(3,d.energy/maxBar*100)}%`}}/></div><b className="text-right">{fmt(d.energy,2)} kWh</b></div>):<div className="py-12 text-center text-xs text-slate-400">No readings for this period.</div>}</div></div><div className="bg-white border border-slate-200 rounded-xl overflow-hidden"><div className="px-5 py-4 border-b border-slate-200"><h2 className="font-black text-sm">Telemetry history</h2><p className="text-[10px] text-slate-500">{filtered.length} readings • newest first</p></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr>{['Time','Client','Inverter','PV','Load','SOC','Daily','Cumulative','Status',''].map(h=><th key={h} className="px-3 py-2.5 text-left text-[10px] uppercase tracking-wider text-slate-500">{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-3 py-2.5 whitespace-nowrap">{new Date(r.timestamp).toLocaleString('en-KE')}</td><td className="px-3 py-2.5">{r.clientName||r.clientRef}</td><td className="px-3 py-2.5">{r.inverterModel||'-'}</td><td className="px-3 py-2.5">{fmt(r.pvPowerKw)} kW</td><td className="px-3 py-2.5">{fmt(r.loadPowerKw)} kW</td><td className="px-3 py-2.5">{fmt(r.batterySoc)}%</td><td className="px-3 py-2.5">{fmt(r.dailyEnergyKwh,2)}</td><td className="px-3 py-2.5">{fmt(r.totalEnergyKwh,2)}</td><td className="px-3 py-2.5"><span className={`px-2 py-1 rounded-full text-[9px] font-black ${r.status==='Online'?'bg-emerald-50 text-emerald-700':r.status==='Warning'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{r.status}</span></td><td className="px-3"><button onClick={()=>remove(r.id)} className="text-slate-400 hover:text-rose-600"><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-xs text-slate-400">No telemetry readings yet.</div>}</div></div></section>
  </div>
 </div>;
};
