import React, { useState } from 'react';
import { Download, FileText, Printer, CheckCircle2 } from 'lucide-react';
import jsPDF from 'jspdf';
import { Appliance, BOQItem, CommercialTerms, CompanySettings, Financials, HardwareItem, Quotation, SizingResult } from '../types';

interface Props { client:any; appliances:Appliance[]; sizing:SizingResult; boq:BOQItem[]; financials:Financials; commercialTerms:CommercialTerms; quoteRef:string; currency:string; settings:CompanySettings; inventory:HardwareItem[]; images:any[]; attachedImageIds?:string[]; onAttachedImagesChange?:(ids:string[])=>void; onSaveAndClearWorkspace:()=>Promise<Quotation>; setActiveTab:(tab:string)=>void; onStartNewQuotation:()=>void; }
const GREEN=[0,158,73] as const, INK=[25,32,39] as const, MUTED=[102,112,133] as const, LINE=[205,211,218] as const, PALE=[247,249,250] as const;
const money=(n:number)=>Number(n||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
const text=(v:any)=>String(v??'').trim()||'—';
const wrap=(pdf:jsPDF,v:any,w:number)=>pdf.splitTextToSize(text(v),w);

export const PDFPreview:React.FC<Props>=({client,appliances,sizing,boq,financials,commercialTerms,quoteRef,currency,settings,onSaveAndClearWorkspace,setActiveTab,onStartNewQuotation})=>{
 const [generating,setGenerating]=useState(false); const [saved,setSaved]=useState(false);
 const download=async()=>{
  if(!client.name?.trim()){alert('Enter the client name before generating the quotation.');return;}
  if(!/^\d{10}$/.test(String(client.phone||''))){alert('Enter a valid 10-digit Kenyan phone number before generating the quotation.');return;}
  if(!boq.length){alert('Build the BOQ before generating the quotation.');return;}
  setGenerating(true);
  try{
   const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});
   const M=13,W=210,R=W-M; let y=13;
   const header=()=>{pdf.setFillColor(...GREEN);pdf.rect(M,10,3,19,'F');pdf.setFont('helvetica','bold');pdf.setTextColor(...INK);pdf.setFontSize(16);pdf.text(text(settings.companyName).toUpperCase(),M+7,16);pdf.setFont('helvetica','normal');pdf.setFontSize(7.5);pdf.setTextColor(...MUTED);pdf.text(text(settings.tagline),M+7,20);pdf.text(text(settings.companyAddress),M+7,24);pdf.text([settings.pobox,settings.companyPhone,settings.companyMobile,settings.companyEmail].filter(Boolean).join(' • '),M+7,28);pdf.setFont('helvetica','bold');pdf.setFontSize(13);pdf.setTextColor(...INK);pdf.text('QUOTATION',R,15,{align:'right'});pdf.setFontSize(8);pdf.text(text(quoteRef),R,20,{align:'right'});pdf.setFont('helvetica','normal');pdf.setTextColor(...MUTED);pdf.text(new Date().toLocaleDateString('en-KE'),R,25,{align:'right'});pdf.setDrawColor(...LINE);pdf.line(M,33,R,33);y=40;};
   const page=()=>{pdf.addPage();header();}; const ensure=(h:number)=>{if(y+h>282)page();};
   const section=(label:string)=>{ensure(12);pdf.setFillColor(...GREEN);pdf.rect(M,y,2.5,6,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.setTextColor(...INK);pdf.text(label.toUpperCase(),M+6,y+5);y+=10;};
   const cellTable=(headers:string[],rows:string[][],widths:number[])=>{ensure(14);let x=M;pdf.setFillColor(...GREEN);pdf.rect(M,y,R-M,8,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(7);pdf.setTextColor(255,255,255);headers.forEach((h,i)=>{pdf.text(h,x+2,y+5);x+=widths[i]});y+=8;rows.forEach((row,ri)=>{const lines=row.map((v,i)=>wrap(pdf,v,widths[i]-4));const h=Math.max(7,Math.max(...lines.map(l=>l.length))*3.8+3);if(y+h>282){page();x=M;pdf.setFillColor(...GREEN);pdf.rect(M,y,R-M,8,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(7);pdf.setTextColor(255,255,255);headers.forEach((h2,i)=>{pdf.text(h2,x+2,y+5);x+=widths[i]});y+=8;}pdf.setFillColor(...(ri%2?PALE:[255,255,255]));pdf.rect(M,y,R-M,h,'F');pdf.setDrawColor(...LINE);pdf.rect(M,y,R-M,h);x=M;pdf.setFont('helvetica','normal');pdf.setFontSize(7.1);pdf.setTextColor(...INK);lines.forEach((ls,i)=>{pdf.text(ls,x+2,y+4);x+=widths[i]});y+=h;});};
   const info=(a:string,b:any,x:number,yy:number)=>{pdf.setFont('helvetica','bold');pdf.setFontSize(6.5);pdf.setTextColor(...MUTED);pdf.text(a.toUpperCase(),x,yy);pdf.setFont('helvetica','normal');pdf.setFontSize(8);pdf.setTextColor(...INK);pdf.text(text(b),x,yy+5);};
   header();
   pdf.setFont('helvetica','bold');pdf.setFontSize(10);pdf.setTextColor(...INK);pdf.text(`RE: QUOTATION FOR SOLAR POWER SOLUTION FOR ${text(client.name).toUpperCase()}`,M,y);y+=5;pdf.setFont('helvetica','normal');pdf.setFontSize(7.5);pdf.setTextColor(...MUTED);pdf.text('Thank you for the interest you have shown in our Solar Power Solution, we are pleased to quote to you as follows:-',M,y);y+=10;
   section('Client & project');
   info('Client',client.name,M,y);info('Client ref',client.refNumber||'—',68,y);info('Quote no.',quoteRef,111,y);info('Date',new Date().toLocaleDateString('en-KE'),R-27,y);y+=13;
   info('Contact',client.contactPerson||'—',M,y);info('Phone',client.phone||'—',68,y);info('Email',client.email||'—',111,y);y+=13;info('Site',client.address||'—',M,y);info('Region',client.region||'—',111,y);y+=11;
   section('Load profile');
   cellTable(['No.','Load description','Qty','W','Total W','Hours / day','Use %','Energy / day (Wh)'],appliances.map((a,i)=>{const total=(a.watts||0)*(a.qty||1);const daily=total*(a.hoursPerDay||0)*((a.usagePercent??100)/100);return[String(i+1),a.name,String(a.qty),money(a.watts),money(total),String(a.hoursPerDay),`${a.usagePercent??100}%`,money(daily)]}),[9,63,12,17,20,24,18,34]);
   ensure(14);pdf.setFont('helvetica','bold');pdf.setFontSize(7.5);pdf.setTextColor(...INK);pdf.text(`Total connected load: ${money(sizing.connectedLoadWatts||0)} W`,M,y+5);pdf.text(`Daily energy: ${money(sizing.totalDailyKwh)} kWh/day`,R,y+5,{align:'right'});y+=11;
   section('System sizing');
   cellTable(['Parameter','Calculated value','Basis'],[
    ['Daily energy demand',`${money(sizing.totalDailyKwh)} kWh/day`,`Day ${money(sizing.dayKwh)} • Night ${money(sizing.nightKwh)}`],
    ['Connected load',`${money((sizing.connectedLoadWatts||0)/1000)} kW`,`Sum of W × quantity`],
    ['Design peak',`${money((sizing.designPeakWatts||sizing.peakWatts)/1000)} kW`,`Connected load × ${Math.round((sizing.coincidenceFactor||.8)*100)}% coincidence`],
    ['Inverter',`${sizing.recommendedInverterKw} kW`,`25% design margin plus largest appliance surge check`],
    ['PV array',`${sizing.recommendedPvArrayKwp} kWp`,`Daily kWh ÷ (sun hours × ${Math.round((sizing.pvDerate||.8)*100)}% derate)`],
    ['PV modules',`${sizing.panelCount} × ${sizing.panelWattage} W`,`Installed PV capacity ${sizing.recommendedPvArrayKwp} kWp`],
    ['Battery bank',`${sizing.recommendedBatteryKwh} kWh / ${sizing.recommendedBatteryAh} Ah`,`Night energy × ${sizing.batteryAutonomyDays||1} day autonomy ÷ ${Math.round(sizing.dod*100)}% DoD`],
    ['System voltage',`${sizing.systemVoltage} V DC`,`Selected design bus voltage`],
   ],[43,52,98]);
   section('Quotation / bill of quantities');
   cellTable(['No.','Item & specification','Qty','Unit','Rate (KSh)','Amount (KSh)'],boq.map((x,i)=>[String(i+1),`${x.description}\n${x.specification}`,String(x.qty),x.unit,money(x.unitPrice),money(x.totalPrice)]),[9,91,14,18,34,31]);
   ensure(29);pdf.setFillColor(...PALE);pdf.rect(112,y,83,27,'F');pdf.setDrawColor(...LINE);pdf.rect(112,y,83,27);pdf.setFont('helvetica','normal');pdf.setFontSize(7.5);pdf.setTextColor(...MUTED);pdf.text('SUBTOTAL',116,y+6);pdf.text('DISCOUNT',116,y+12);pdf.text(`VAT (${financials.vatRate}%)`,116,y+18);pdf.setFont('helvetica','bold');pdf.setTextColor(...INK);pdf.text('GRAND TOTAL',116,y+24);pdf.setTextColor(...GREEN);pdf.text(`${currency}${money(financials.grandTotal)}`,191,y+24,{align:'right'});pdf.setFont('helvetica','normal');pdf.setTextColor(...INK);pdf.text(`${currency}${money(financials.subtotal)}`,191,y+6,{align:'right'});pdf.text(`${currency}${money(financials.discount)}`,191,y+12,{align:'right'});pdf.text(`${currency}${money(financials.vatAmount)}`,191,y+18,{align:'right'});y+=34;
   section('Commercial terms & warranties');
   cellTable(['Term','Details'],[['Payment terms',commercialTerms.paymentTerms],['Installation',commercialTerms.installationPeriod],['PV modules',commercialTerms.warrantyPanels],['Inverter',commercialTerms.warrantyInverter],['Battery',commercialTerms.warrantyBattery],['Validity',`${commercialTerms.validityDays} days from quotation date`]], [42,153]);
   ensure(30);pdf.setDrawColor(...LINE);pdf.line(M,y,R,y);y+=7;pdf.setFont('helvetica','bold');pdf.setFontSize(7.5);pdf.setTextColor(...INK);pdf.text('ORDER CONFIRMATION',M,y);pdf.setFont('helvetica','normal');pdf.text('Purchase order / signed quotation confirmation required before procurement.',M,y+5);y+=14;pdf.setFont('helvetica','bold');pdf.text('NOTE',M,y);pdf.setFont('helvetica','normal');pdf.text('Final electrical string design, protection ratings, voltage drop and equipment compatibility remain subject to site and manufacturer datasheet verification.',M+18,y,{maxWidth:R-M-18});
   ensure(16);y=276;pdf.setDrawColor(...LINE);pdf.line(M,y,R,y);y+=6;pdf.setFont('helvetica','bold');pdf.setFontSize(7);pdf.setTextColor(...INK);pdf.text(text(settings.companyName).toUpperCase(),M,y);pdf.setFont('helvetica','normal');pdf.setTextColor(...MUTED);pdf.text([settings.companyPhone,settings.companyMobile,settings.companyEmail,settings.companyWebsite].filter(Boolean).join(' • '),R,y,{align:'right'});
   const safe=(client.name||'Client').replace(/[^a-z0-9]+/gi,'_').replace(/^_+|_+$/g,''); const filename=`${quoteRef||'Quotation'}_${safe||'Client'}.pdf`;
   pdf.save(filename);
   await onSaveAndClearWorkspace(); setSaved(true);
  }catch(e){console.error(e);alert(`PDF generation failed. The quotation was NOT cleared.\n\n${e instanceof Error?e.message:'Please try again.'}`)}finally{setGenerating(false)}
 };
 return <div className="page-stack">
  <section className="page-header"><div className="page-heading"><div className="section-icon"><FileText size={18}/></div><div><div className="eyebrow">Customer document</div><h1>Quotation preview</h1><p>Customer-facing document follows the clean commercial style: white page, restrained green, compact tables and only information needed to understand the proposal.</p></div></div><div className="toolbar-actions"><button className="btn-secondary" onClick={()=>window.print()}><Printer size={14}/> Print</button><button className="btn-primary" disabled={generating} onClick={download}><Download size={14}/>{generating?'Creating PDF…':'Download PDF'}</button></div></section>
  {saved&&<div className="panel" style={{padding:14,display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}}><div style={{display:'flex',alignItems:'center',gap:8,fontSize:12,color:'#12633a'}}><CheckCircle2 size={16}/> Quotation downloaded and archived. Your browser will place the PDF in its normal Downloads folder.</div><button className="btn-primary btn-small" onClick={()=>{setSaved(false);onStartNewQuotation();setActiveTab('client')}}>New quotation</button></div>}
  <section className="panel"><div className="panel-head"><div><div className="eyebrow">Full customer document</div><h2>Final quotation preview</h2><p style={{margin:0,fontSize:11,color:'#667085'}}>This is the complete customer-facing document. The downloaded PDF uses the same information and order.</p></div></div><div className="quote-paper">
<div className="quote-paper-head"><div><div className="quote-brand">{String(settings.companyName||'ONE INVERTER').toUpperCase()}</div><div className="quote-muted">{text(settings.tagline)}</div><div className="quote-muted">{text(settings.companyAddress)}</div><div className="quote-muted">{[settings.pobox,settings.companyPhone,settings.companyMobile,settings.companyEmail].filter(Boolean).join(' • ')}</div></div><div className="quote-title"><b>QUOTATION</b><span>{quoteRef}</span><span>{new Date().toLocaleDateString('en-KE')}</span></div></div>
<div className="quote-rule"/><h3>RE: QUOTATION FOR SOLAR POWER SOLUTION FOR {text(client.name).toUpperCase()}</h3><p className="quote-intro">Thank you for the interest you have shown in our Solar Power Solution, we are pleased to quote to you as follows:-</p>
<div className="quote-section">CLIENT & PROJECT</div><div className="quote-info-grid"><div><small>CLIENT</small><b>{text(client.name)}</b></div><div><small>CLIENT REF</small><b>{text(client.refNumber)}</b></div><div><small>QUOTE REF</small><b>{text(quoteRef)}</b></div><div><small>DATE</small><b>{new Date().toLocaleDateString('en-KE')}</b></div><div><small>CONTACT</small><b>{text(client.contactPerson)}</b></div><div><small>PHONE</small><b>{text(client.phone)}</b></div><div><small>EMAIL</small><b>{text(client.email)}</b></div><div><small>SITE</small><b>{text(client.address)}</b></div></div>
<div className="quote-section">LOAD PROFILE</div><table className="quote-table"><thead><tr><th>#</th><th>Load description</th><th>Qty</th><th>W</th><th>Total W</th><th>Hours</th><th>Use %</th><th>Daily Wh</th></tr></thead><tbody>{appliances.map((a,i)=>{const total=(a.watts||0)*(a.qty||1);const daily=total*(a.hoursPerDay||0)*((a.usagePercent??100)/100);return <tr key={a.id||i}><td>{i+1}</td><td>{a.name}</td><td>{a.qty}</td><td>{money(a.watts)}</td><td>{money(total)}</td><td>{a.hoursPerDay}</td><td>{a.usagePercent??100}%</td><td>{money(daily)}</td></tr>})}</tbody></table><div className="quote-total-line"><b>Total connected load: {money(sizing.connectedLoadWatts||0)} W</b><b>Daily energy: {money(sizing.totalDailyKwh)} kWh/day</b></div>
<div className="quote-section">ENGINEERING SIZING</div><table className="quote-table sizing"><thead><tr><th>Parameter</th><th>Calculated value</th><th>Basis</th></tr></thead><tbody><tr><td>Daily energy demand</td><td>{money(sizing.totalDailyKwh)} kWh/day</td><td>Day {money(sizing.dayKwh)} • Night {money(sizing.nightKwh)}</td></tr><tr><td>Connected load</td><td>{money((sizing.connectedLoadWatts||0)/1000)} kW</td><td>Sum of W × quantity</td></tr><tr><td>Design peak</td><td>{money((sizing.designPeakWatts||sizing.peakWatts)/1000)} kW</td><td>Connected load × {Math.round((sizing.coincidenceFactor||.8)*100)}% coincidence</td></tr><tr><td>Inverter</td><td>{sizing.recommendedInverterKw} kW</td><td>25% design margin plus surge check</td></tr><tr><td>PV array</td><td>{sizing.recommendedPvArrayKwp} kWp</td><td>Daily kWh ÷ (sun hours × {Math.round((sizing.pvDerate||.8)*100)}% derate)</td></tr><tr><td>PV modules</td><td>{sizing.panelCount} × {sizing.panelWattage} W</td><td>Installed PV capacity</td></tr><tr><td>Battery bank</td><td>{sizing.recommendedBatteryKwh} kWh / {sizing.recommendedBatteryAh} Ah</td><td>Night energy × autonomy ÷ DoD</td></tr><tr><td>System voltage</td><td>{sizing.systemVoltage} V DC</td><td>Selected design bus voltage</td></tr></tbody></table>
<div className="quote-section">BILL OF QUANTITIES</div><table className="quote-table boq-preview"><thead><tr><th>#</th><th>Item & specification</th><th>Qty</th><th>Unit</th><th>Rate (KSh)</th><th>Amount (KSh)</th></tr></thead><tbody>{boq.map((x,i)=><tr key={x.id}><td>{i+1}</td><td><b>{x.description}</b><br/><span>{x.specification}</span></td><td>{x.qty}</td><td>{x.unit}</td><td>{money(x.unitPrice)}</td><td>{money(x.totalPrice)}</td></tr>)}</tbody></table><div className="quote-grand"><div>SUBTOTAL <b>{currency}{money(financials.subtotal)}</b></div><div>DISCOUNT <b>{currency}{money(financials.discount)}</b></div><div>VAT ({financials.vatRate}%) <b>{currency}{money(financials.vatAmount)}</b></div><div className="grand">GRAND TOTAL <b>{currency}{money(financials.grandTotal)}</b></div></div>
<div className="quote-section">COMMERCIAL TERMS & WARRANTIES</div><table className="quote-table sizing"><tbody>{[['Payment terms',commercialTerms.paymentTerms],['Installation',commercialTerms.installationPeriod],['PV modules',commercialTerms.warrantyPanels],['Inverter',commercialTerms.warrantyInverter],['Battery',commercialTerms.warrantyBattery],['Validity',`${commercialTerms.validityDays} days from quotation date`]].map(([a,b])=><tr key={a as string}><td><b>{a}</b></td><td colSpan={2}>{b}</td></tr>)}</tbody></table><div className="quote-note"><b>ORDER CONFIRMATION</b><br/>Purchase order / signed quotation confirmation required before procurement.<br/><br/><b>NOTE</b><br/>Final electrical string design, protection ratings, voltage drop and equipment compatibility remain subject to site and manufacturer datasheet verification.</div></div></section>
  <section className="panel" style={{padding:18}}><div className="eyebrow">PDF content</div><h2 style={{margin:'4px 0 4px',fontSize:15}}>What the customer will receive</h2><p style={{margin:0,fontSize:11,color:'#667085',lineHeight:1.55}}>Quotation header, client/project details, load profile, concise system sizing, bill of quantities, commercial totals, warranties and commercial notes. Product images, database metadata, source documents and internal engineering notes are deliberately kept out of the customer document.</p></section>
 </div>;
};
